In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def getsolarprediction(daywanted):
    
    r = pd.read_csv('Data/solarprediction.csv')
    
    return r[daywanted]

In [3]:
def getsolarsupply(daywanted):
    
    efficiency = 0.2
    roofarea = 8000
    


    SOLAR = pd.read_csv('Data/oxon_solar_2014.csv')

    SOLAR = SOLAR[((daywanted-1)*24):(24+(daywanted-1)*24)]
    
    SOLAR['Total Supply (kWh)'] = SOLAR['kW']*roofarea*efficiency
    
    SOLAR.rename(index={0+(daywanted-1)*24:'00:00',1+(daywanted-1)*24:'01:00',2+(daywanted-1)*24:'02:00',3+(daywanted-1)*24:'03:00',4+(daywanted-1)*24:'04:00',5+(daywanted-1)*24:'05:00',6+(daywanted-1)*24:'06:00',7+(daywanted-1)*24:'07:00',8+(daywanted-1)*24:'08:00',9+(daywanted-1)*24:'09:00',10+(daywanted-1)*24:'10:00',11+(daywanted-1)*24:'11:00',12+(daywanted-1)*24:'12:00',13+(daywanted-1)*24:'13:00',14+(daywanted-1)*24:'14:00',15+(daywanted-1)*24:'15:00',16+(daywanted-1)*24:'16:00',17+(daywanted-1)*24:'17:00',18+(daywanted-1)*24:'18:00',19+(daywanted-1)*24:'19:00',20+(daywanted-1)*24:'20:00',21+(daywanted-1)*24:'21:00',22+(daywanted-1)*24:'22:00',23+(daywanted-1)*24:'23:00'}, inplace=True)
    
    SOLAR = SOLAR.drop(['Datetime','kW'], axis = 1)
    
    return SOLAR

In [4]:
solar = getsolarsupply(2)
solar

       Total Supply (kWh)
00:00                 0.0
01:00                 0.0
02:00                 0.0
03:00                 0.0
04:00                 0.0
05:00                 0.0
06:00                 0.0
07:00                 0.0
08:00                 3.2
09:00                86.4
10:00               340.8
11:00               580.8
12:00               598.4
13:00               419.2
14:00               152.0
15:00                44.8
16:00                 0.0
17:00                 0.0
18:00                 0.0
19:00                 0.0
20:00                 0.0
21:00                 0.0
22:00                 0.0
23:00                 0.0

In [5]:
daywanted = 1

efficiency = 0.2
roofarea = 8000



SOLAR = pd.read_csv('Data/oxon_solar_2014.csv')

SOLAR = SOLAR[((daywanted-1)*24):(24+(daywanted-1)*24)]

SOLAR['Total Supply (kWh)'] = SOLAR['kW']*roofarea*efficiency

SOLAR.rename(index={0+(daywanted-1)*24:'00:00',1+(daywanted-1)*24:'01:00',2+(daywanted-1)*24:'02:00',3+(daywanted-1)*24:'03:00',4+(daywanted-1)*24:'04:00',5+(daywanted-1)*24:'05:00',6+(daywanted-1)*24:'06:00',7+(daywanted-1)*24:'07:00',8+(daywanted-1)*24:'08:00',9+(daywanted-1)*24:'09:00',10+(daywanted-1)*24:'10:00',11+(daywanted-1)*24:'11:00',12+(daywanted-1)*24:'12:00',13+(daywanted-1)*24:'13:00',14+(daywanted-1)*24:'14:00',15+(daywanted-1)*24:'15:00',16+(daywanted-1)*24:'16:00',17+(daywanted-1)*24:'17:00',18+(daywanted-1)*24:'18:00',19+(daywanted-1)*24:'19:00',20+(daywanted-1)*24:'20:00',21+(daywanted-1)*24:'21:00',22+(daywanted-1)*24:'22:00',23+(daywanted-1)*24:'23:00'}, inplace=True)

SOLAR = SOLAR.drop(['Datetime','kW'], axis = 1)

In [6]:
SOLAR.sum()

Total Supply (kWh)    80.0
dtype: float64

In [8]:
getsolarprediction(1)

KeyError: 1

In [9]:
r = pd.read_csv('Data/solarprediction.csv')

In [12]:
r

     Unnamed: 0            0
0             1  1289.653333
1             2  1289.653333
2             3  1289.653333
3             4  1289.653333
4             5  1289.653333
..          ...          ...
360         361  1717.173333
361         362  1717.173333
362         363  1717.173333
363         364  1717.173333
364         365  1717.173333

[365 rows x 2 columns]